# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Getctx < Formula
  desc "A CLI tool to consolidate source code into a single context file."
  homepage "https://github.com/kacperzielinskidev/getctx"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kacperzielinskidev/getctx/releases/download/v1.0.0/getctx_1.0.0_darwin_amd64.tar.gz"
      sha256 "29ad8241e5515f5d64a045d473840ada3371514d74cc1d3948fb64cb5d981370"

      def install
        bin.install "getctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kacperzielinskidev/getctx/releases/download/v1.0.0/getctx_1.0.0_darwin_arm64.tar.gz"
      sha256 "d13b6c29e758611250b246eab130f83e2a764445acb90fc1df3244b5a95119b8"

      def install
        bin.install "getctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kacperzielinskidev/getctx/releases/download/v1.0.0/getctx_1.0.0_linux_amd64.tar.gz"
      sha256 "6cf7c7fb515b086a02a6116aa3ded2628272967877879a4aa315460ddcbc60cd"
      def install
        bin.install "getctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kacperzielinskidev/getctx/releases/download/v1.0.0/getctx_1.0.0_linux_arm64.tar.gz"
      sha256 "fa780d47bc86cddfe31d5ee8c669bf319172d86e626a1617d9a1f00518c4dd82"
      def install
        bin.install "getctx"
      end
    end
  end
end
