# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Getctx < Formula
  desc "A CLI tool to consolidate source code into a single context file."
  homepage "https://github.com/kacperzielinskidev/getctx"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kacperzielinskidev/getctx/releases/download/v1.0.1/getctx_1.0.1_darwin_amd64.tar.gz"
      sha256 "e9c1e4ba3bc36b8751acd065f9ee5c70aadf2dfb30fbee9fc9b666a0e41c832c"

      def install
        bin.install "getctx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kacperzielinskidev/getctx/releases/download/v1.0.1/getctx_1.0.1_darwin_arm64.tar.gz"
      sha256 "4a30b247271b738241e3dc7d33917df832671f75c4ab6b3472aebe9a543d9cf5"

      def install
        bin.install "getctx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kacperzielinskidev/getctx/releases/download/v1.0.1/getctx_1.0.1_linux_amd64.tar.gz"
      sha256 "8b1f30233e097566f5d13416f365663561f1ffad98c3639754d4ae0e4ccb8518"
      def install
        bin.install "getctx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kacperzielinskidev/getctx/releases/download/v1.0.1/getctx_1.0.1_linux_arm64.tar.gz"
      sha256 "1b409b18e0e86dffe57e37761a822a9a372b57a3941ab4672f4efa456bda15b9"
      def install
        bin.install "getctx"
      end
    end
  end
end
